In [105]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [106]:
data = 'https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/course_lead_scoring_2026.csv'
#!wget $data -O homework-week-3.csv
df = pd.read_csv('homework-week-3.csv')
df

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NaN,NaN,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1
...,...,...,...,...,...,...,...,...,...
4995,organic_search,education,employed,asia,45834.0,2,2,0.37,1
4996,NaN,technology,employed,north_america,84831.0,2,5,0.51,0
4997,organic_search,finance,employed,asia,53636.0,4,6,0.75,1
4998,referral,technology,employed,africa,69430.0,4,8,0.79,1
4999,referral,technology,employed,europe,81355.0,6,11,0.99,1

In [107]:
df.dtypes

lead_source                     str
industry                        str
employment_status               str
location                        str
annual_income               float64
number_of_courses_viewed      int64
interaction_count             int64
lead_score                  float64
converted                     int64
dtype: object

In [108]:
df.isnull().sum()

lead_source                 148
industry                    240
employment_status           194
location                    208
annual_income               369
number_of_courses_viewed      0
interaction_count             0
lead_score                   35
converted                     0
dtype: int64

In [109]:
len(df)

5000

In [111]:
categorical = list(df.dtypes[df.dtypes == 'str'].index)
categorical

['lead_source', 'industry', 'employment_status', 'location']

In [112]:
numerical_colums = list(df.dtypes[df.dtypes != 'str'].index)
numerical_colums

['annual_income',
 'number_of_courses_viewed',
 'interaction_count',
 'lead_score',
 'converted']

In [113]:
df.annual_income = df.annual_income.fillna(0)
df.number_of_courses_viewed = df.number_of_courses_viewed.fillna(0)
df.interaction_count = df.interaction_count.fillna(0)
df.lead_score = df.lead_score.fillna(0)
df.isnull().sum()

lead_source                 148
industry                    240
employment_status           194
location                    208
annual_income                 0
number_of_courses_viewed      0
interaction_count             0
lead_score                    0
converted                     0
dtype: int64

In [114]:
df.lead_source = df.lead_source.fillna(0)
df.industry = df.industry.fillna(0)
df.employment_status = df.employment_status.fillna(0)
df.location = df.location.fillna(0)


df.lead_source = df.lead_source.replace([0,'0'], 'NA')
df.industry = df.industry.replace([0,'0'], 'NA')
df.employment_status = df.employment_status.replace([0,'0'], 'NA')
df.location = df.location.replace([0,'0'], 'NA')
df.isnull().sum()

lead_source                 0
industry                    0
employment_status           0
location                    0
annual_income               0
number_of_courses_viewed    0
interaction_count           0
lead_score                  0
converted                   0
dtype: int64

In [115]:
df

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NA,0.0,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1
...,...,...,...,...,...,...,...,...,...
4995,organic_search,education,employed,asia,45834.0,2,2,0.37,1
4996,NA,technology,employed,north_america,84831.0,2,5,0.51,0
4997,organic_search,finance,employed,asia,53636.0,4,6,0.75,1
4998,referral,technology,employed,africa,69430.0,4,8,0.79,1
4999,referral,technology,employed,europe,81355.0,6,11,0.99,1

In [116]:
## Q1
df['industry'].value_counts()

industry
technology       1173
retail            925
healthcare        840
finance           720
education         639
manufacturing     463
NA                240
Name: count, dtype: int64

In [117]:
df['employment_status'].value_counts()

employment_status
employed         2633
student           760
self_employed     715
unemployed        698
NA                194
Name: count, dtype: int64

In [135]:
df['lead_source'].value_counts()

lead_source
organic_search    1251
paid_ads          1140
social_media      1055
referral           790
events             616
NA                 148
Name: count, dtype: int64

In [119]:
df['location'].value_counts()

location
north_america    1371
europe           1149
asia             1052
south_america     749
africa            471
NA                208
Name: count, dtype: int64

In [120]:
df['industry'].mode()

0    technology
Name: industry, dtype: object

In [121]:
##Q2
corr1 = df.interaction_count.corr(df.lead_score)
corr2 = df.number_of_courses_viewed .corr(df.lead_score)
corr3 = df.number_of_courses_viewed .corr(df.interaction_count)
corr4 = df.annual_income.corr(df.interaction_count)
print("Correction between 'interaction_count' and 'lead_score' \t\t" ,corr1 )
print("Correction between 'number_of_courses_viewed' and 'lead_score' \t\t" ,corr2 )
print("Correction between 'number_of_courses_viewed' and 'interaction_count' \t" ,corr3 )
print("Correction between 'annual_income' and 'lead_score' \t\t\t" ,corr4 )

Correction between 'interaction_count' and 'lead_score' 		 0.9157457980418677
Correction between 'number_of_courses_viewed' and 'lead_score' 		 0.7572042392104887
Correction between 'number_of_courses_viewed' and 'interaction_count' 	 0.7216090038937009
Correction between 'annual_income' and 'lead_score' 			 0.12284235135955954

In [122]:
from sklearn.model_selection import train_test_split

df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)
len(df_test), len(df_train), len(df_val)

(1000, 3000, 1000)

In [123]:
##Q3
from sklearn.metrics import mutual_info_score
score1 = mutual_info_score(df.converted,df.industry)
score2 = mutual_info_score(df.converted,df.location)
score3 = mutual_info_score(df.converted,df.lead_source)
score4 = mutual_info_score(df.converted,df.employment_status)
print("mutual info score  between 'converted' and 'industry' \t\t" ,score1)
print("mutual info score  between 'converted' and 'location' \t\t" ,score2)
print("mutual info score  between 'converted' and 'lead_source' \t" ,score3)
print("mutual info score  between 'converted' and 'employment_status' \t" ,score4)

mutual info score  between 'converted' and 'industry' 		 0.0022800937730549087
mutual info score  between 'converted' and 'location' 		 0.0010636898089210062
mutual info score  between 'converted' and 'lead_source' 	 0.033063899391404215
mutual info score  between 'converted' and 'employment_status' 	 0.022797267862555814

In [124]:
##Q4
df_train = df_train.reset_index(drop = 'True')
df_val = df_val.reset_index(drop = 'True')
df_test = df_test.reset_index(drop = 'True')

y_train = df_train.converted.values
y_val = df_val.converted.values
y_test = df_test.converted.values

del df_train['converted']
del df_val['converted']
del df_test['converted']

np.float64(0.57075)

In [163]:
numerical = ['annual_income',
 'number_of_courses_viewed',
 'interaction_count',
 'lead_score']

from sklearn.feature_extraction import DictVectorizer

dv = DictVectorizer(sparse=False)

train_dict = df_train[categorical + numerical].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

val_dict = df_val[categorical + numerical].to_dict(orient='records')
X_val = dv.transform(val_dict)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
model.fit(X_train, y_train)

LogisticRegression()
y_pred = model.predict_proba(X_val)[:, 1]
converted_decision = (y_pred >= 0.5)

(y_val == converted_decision).mean()

np.float64(0.645)